routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {

    return view('login');
});*/


Auth::routes();

	Route::get('password/reset', 'Auth\FrontendForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::get('password/confirm/{token}', 'EmailController@confirm')->name('password.confirm');
	Route::post('password/reset/change-password', 'EmailController@change_password')->name('password.change-password');
	Route::post('password/email', 'EmailController@reset_password')->name('password.email');
	Route::get('password/reset/{token}', 'Auth\FrontendResetPasswordController@showResetForm')->name('password.reset');
	Route::post('password/reset', 'Auth\FrontendResetPasswordController@reset')->name('password.update');

	// quên mật khẩu admin
	Route::get('admin-password/reset', 'Auth\ForgotPasswordController@showLinkRequestFormAdmin')->name('admin-password.request');
	Route::post('admin-password/email', 'EmailController@reset_password_admin')->name('admin-password.email');

	Route::get('admin-password/reset/{token}', 'Auth\ResetPasswordController@showResetFormAdmin')->name('admin-password.reset');
	Route::post('admin-password/reset', 'Auth\ResetPasswordController@reset')->name('admin-password.update');

	Route::get('admin-password/confirm/{token}', 'EmailController@confirm_admin')->name('admin-password.confirm');
	Route::post('admin-password/reset/change-password', 'EmailController@change_password_admin')->name('admin-password.change-password');


Route::namespace('Frontend')->group(function() {
	Route::get('','HomeController@index')->name('home');
	
	Route::get('product-category-parent/{alias}','HomeController@get_category_parent')->name('product-category-parent');
	Route::get('product-category/{alias}/{parent}','HomeController@product_category')->name('product-category');
	Route::get('product-detail/{alias}','HomeController@product_detail')->name('product-detail');
	
	Route::get('gioi-thieu','HomeController@about')->name('gioi-thieu');

	Route::get('project','HomeController@project_news')->name('project');
	Route::get('project-detail/{alias}','HomeController@project_detail')->name('project-detail');

	Route::get('tin-tuc-su-kien','HomeController@getNews')->name('news');
	Route::get('tin-tuc-su-kien/{alias}','HomeController@news_detail')->name('news-detail');

	Route::get('danh-muc-tin-tuc/{id}/{alias}','HomeController@newsCategory')->name('news-category');

	Route::get('tuyen-dung','HomeController@recruitment')->name('tuyen-dung');
	Route::get('chi-tiet-tuyen-dung/{alias}','HomeController@tuyendung_detail')->name('chi-tiet-tuyen-dung');

	Route::get('contact-company','HomeController@ContactCompany')->name('contact-company');
	Route::get('lien-he','HomeController@contactUs')->name('lien-he');
	Route::post('lien-he','HomeController@storeContact')->name('lien-he.store');

	Route::get('dangnhap','HomeController@getDangnhap')->name('dangnhap');
	Route::post('dangnhap','HomeController@postDangnhap');

	Route::get('register', 'HomeController@RegisterAccount');
	Route::get('registersucces', 'HomeController@Registersucces');
	
	Route::get('dangky','HomeController@getDangky')->name('dangky');
	Route::post('dangky','HomeController@postDangky');

	Route::get('dangxuat','HomeController@getDangxuat')->name('dangxuat');

	Route::get('tin-dang','HomeController@create')->name('quanlytk.create');
	Route::post('tin-dang','HomeController@store')->name('quanlytk.store');
	Route::get('tin-dang/{alias}','HomeController@edit')->name('quanlytd.edit');
	Route::post('tin-dang/{alias}','HomeController@update')->name('quanlytd.update');
	Route::get('tin-dang/{id}/delete','HomeController@destroyQuanlytd')->name('quanlytk.destroy');

	Route::get('quan-ly-tai-khoan','HomeController@editQuanlytk')->name('quanlytk.edit');
	Route::post('quan-ly-tai-khoan','HomeController@updateQuanlytk')->name('quanlytk.update');
	
	Route::post('change-password','HomeController@updateChangePassword')->name('changepass.update');

	Route::get('timkiem','HomeController@get_timkiem')->name('timkiem');
	Route::post('timkiem','HomeController@timkiem')->name('timkiem');

});


Route::get('loginbds','LoginController@getLogin')->middleware('loginal')->name('getLogin');
Route::post('loginbds','LoginController@postLogin');
Route::get('logout','LoginController@getLogout')->name('getLogout');


Route::namespace('Backend')->middleware('login')->prefix('admin')->group(function(){
	 Route::resource('/','HomeController');
	 // Route::resource('useradmin','AdminController');
	 Route::get('index','AdminController@index')->name('useradmin.index');
	 Route::get('add','AdminController@create')->name('useradmin.create');
	 Route::post('add','AdminController@store')->name('useradmin.store');
	 Route::get('edit/{id}','AdminController@edit')->name('useradmin.edit');
	 Route::post('edit/{id}','AdminController@update')->name('useradmin.update');
	 Route::get('delete/{id}','AdminController@destroy')->name('useradmin.destroy');

	 Route::get('change-password','AdminController@Getchangepass')->name('change-password');
	 Route::post('change-password','AdminController@Postchangepass');

	 Route::resource('dmtd','DMTDController');
	 Route::resource('dmtt','DMTTController');
	 Route::resource('duan','DuAnController');
	 Route::resource('lienhe','LienHeController');
	 Route::resource('member','MemberController');
	 Route::resource('menu','MenuController');
	 Route::resource('slider','SliderController');
	 Route::resource('tindang','TinDangController');
	 Route::resource('tintuc','TinTucController');
	 Route::resource('tuyendung','TuyenDungController');
	 Route::resource('video','VideoController');
	 Route::resource('gioithieu','IntroduceController');
	 Route::resource('logo','LogoController');
	 Route::resource('mangxahoi','SocialNetworkController');
	 Route::resource('googlemap','GoogleMapController');
	 Route::resource('contactus','ContactUsController');
	 Route::resource('footer','FooterController');
	 Route::resource('cauhinhkhac','ConfigurationController');
});

Route::get('clear-cache','LoginController@clear_cache');

app/Models/DMTT.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DB;

class DMTT extends Model
{
    protected $table = "bds_dmtt";
    public $timestamp = false;
    public function dbdmtt()
    {
    	return DB::table('bds_dmtt');
    }
    public function listindex()
    {
    	return $this->dbdmtt()->get()->toArray();
    }
    public function adddmtt($data)
    {
    	return $this->dbdmtt()->insert($data);
    }
    public function showEdit($id)
    {
    	return $this->dbdmtt()->find($id);
    }
    public function updatedmtt($data,$id)
    {
    	return $this->dbdmtt()->whereId($id)->update($data);
    }
    public function delnews($data)
    {
        return $this->dbdmtt()->delete($data);
    }

    public function NewsIdParent($id) 
    {
        return $this->dbdmtt()->where("parent_id",$id)->get()->toArray();
    }
}

app/Http/Controllers/Backend/DMTTController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Requests\DMTT\DMTTRequest;
use App\Http\Controllers\Controller;
use App\Models\DMTT;
use DB,DateTime;

class DMTTController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    private $dmtt;
    public function __construct(DMTT $dmtt)
    {
        $this->dmtt = $dmtt;
    }
    public function createDMTT($request)
    {
        $data = array(
            'name'      => $request->name,
            'alias'     => (empty($request->alias))? str_slug($request->name,"-") : $request->alias,
            'parent_id' => $request->parent_id,
            'created_at'=> new DateTime
        );
        return $data;
    }
    public function index()
    {
        $data['cate']  = $this->dmtt->listindex();

        return view('admin.modules.dmtt.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $data['menus'] = DB::table('bds_dmtt')->select('id','name','parent_id')->get()->toArray();

        return view('admin.modules.dmtt.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DMTTRequest $request)
    {
        $data = $this->createDMTT($request);    

        $this->dmtt->adddmtt($data);

       return redirect()->route('dmtt.index')->with('success',"message.store_required");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         // $data['menus'] = DB::table('bds_dmtt')->select('id','name','parent_id')->get()->toArray();

        $data['cate'] = $this->dmtt->showEdit($id);

        return view('admin.modules.dmtt.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $data = $this->createDMTT($request);        

         $this->dmtt->updatedmtt($data,$id);
         
         return redirect()->route('dmtt.index')->with('success',"message.update_required");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $data = $request->chk;
       for ($i = 0; $i < count($data); $i++){

                 $this->dmtt->delnews($data[$i]);
            }
            
       return redirect()->route('dmtt.index')->with('success',"message.delete_required"); 
    }
    
}

resources/views/admin/modules/dmtt/create.blade.php
@extends('admin.master')
@section('title','Thêm Danh Mục Tin Tức')
@section('content')
@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('dmtt.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Thêm</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection
<div class="content">
    <!-- Form validation -->
    <div class="card">
        <div class="card-body">
        	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
            <form class="form-validate-jquery" action="{{route('dmtt.store')}}" method="POST" enctype="multipart/form-data">
            	@csrf
                <fieldset class="mb-3">
                    <legend class="text-uppercase font-size-sm font-weight-bold">{{trans('template.Add CateNews')}}</legend>

                    <div class="form-group col-sm-12 row"> 
                        <div class="col-sm-6">
                            <label class="lable_edit">{{trans('template.Name CateNews')}}<span class="text-danger">*</span></label>
                            <input value="{{old('name')}}" type="text" name="name" class="form-control" required="" >
                        </div>                                                                   
                        <div class="col-sm-6">
                            <label class="lable_edit">{{trans('template.Parent CateNews')}}<span class="text-danger">*</span></label>
                            <select name="parent_id" class="form-control">
                               <option value="0">ROOT</option>                               
                           </select>
                        </div>    
                    </div>
                </fieldset>

                <div class="d-flex justify-content-center align-items-center">
                    <button type="reset" class="btn btn-light" id="reset">{{trans('template.Reset')}}<i class="icon-reload-alt ml-2"></i></button>
                    <button type="submit" class="btn btn-primary ml-3">{{trans('template.Submit')}}<i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /form validation -->

</div>
@endsection

resources/views/admin/modules/dmtt/edit.blade.php
@extends('admin.master')
@section('title','Sửa Danh Mục Tin Tức')
@section('content')
@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('dmtt.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Cập nhật</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection
<div class="content">
    <!-- Form validation -->
    <div class="card">
        <div class="card-body">
        	@if ($errors->any())
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
            <form class="form-validate-jquery" action="{{route('dmtt.update',['id'=> $cate->id])}}" method="POST" enctype="multipart/form-data">
                @method('PUT')
            	@csrf
                <fieldset class="mb-3">
                    <legend class="text-uppercase font-size-sm font-weight-bold">{{trans('template.Add CateNews')}}</legend>

                    <div class="form-group col-sm-12 row"> 
                        <div class="col-sm-6">
                            <label class="lable_edit">{{trans('template.Name CateNews')}}<span class="text-danger">*</span></label>
                            <input value="{{old('name',$cate->name)}}" type="text" name="name" class="form-control" required="" >
                        </div>                                                                   
                        <div class="col-sm-6">
                            <label class="lable_edit">{{trans('template.Parent CateNews')}}<span class="text-danger">*</span></label>
                            <select name="parent_id" class="form-control">
                               <option value="0">ROOT</option>                               
                           </select>
                        </div>    
                    </div>
                   
                </fieldset>

                <div class="d-flex justify-content-center align-items-center">
                    <button type="reset" class="btn btn-light" id="reset">{{trans('template.Reset')}}<i class="icon-reload-alt ml-2"></i></button>
                    <button type="submit" class="btn btn-primary ml-3">{{trans('template.Update')}}<i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
    <!-- /form validation -->

</div>
@endsection

resources/views/admin/modules/dmtt/index.blade.php
@extends('admin.master') 
@section('title','Danh Sách Danh Mục Tin Tức') 
@section('content')
@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('dmtt.index')}}" class="breadcrumb-item">Danh sách</a>
                {{-- <span class="breadcrumb-item active"></span> --}}
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection
@include('admin.blocks.alert')

<div class="content">

    <!-- Page length options -->
    <div class="card">
        <div class="card-header header-elements-inline">
            <h5 class="card-title">{{trans('template.List CateNews')}}</h5>
            <div class="header-elements">
                <div class="list-icons">
                    <a class="list-icons-item" data-action="collapse"></a>
                    <a class="list-icons-item" data-action="reload"></a>
                    <a class="list-icons-item" data-action="remove"></a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <a href="{{route('dmtt.create')}}">
                <button type="button" class="btn btn-primary">Thêm Danh mục</button>
            </a>
        </div>
        <form action="{{route('dmtt.destroy',['action'=>'delete'])}}" name="listForm" method="POST">
            @method('DELETE')
            @csrf
        <table class="table datatable-show-all">
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" name="chkall"  onClick="checkallClick(this);">
                    </th>
                    <th>#</th>
                    <th>Tên Danh Mục</th>
                    <th>Alias</th>
                    <th>Hoạt động</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
            	@foreach($cate as $item)
                <tr>
                    <td>
                        <input type="checkbox" name="chk[]" value="{{$item->id}}">
                    </td>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$item->name}}</td>
                    <td>{{$item->alias}}</td>
                    <td>{{ \Carbon\Carbon::createFromTimeStamp(strtotime($item ->created_at))->diffForHumans() }}</td>
                    <td class="text-center">                       
                        <a href="{{ route('dmtt.edit',['dmtt' => $item->id]) }}" class="list-icons-item text-primary-600" title="Sửa"><i class="icon-pencil7"></i></a> &nbsp;
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
            <button type="submit" class="btn btn-danger" onclick="return acceptDelete()" style="margin-left: 10px" title="Xóa">
            <i class="icon-trash" aria-hidden="true"></i></button><br/><br>           
        </form>
    </div>
    <!-- /page length options -->
</div>
@endsection